import React from 'react'
import { Link } from 'react-router-dom'

const TermsConditions = () => {
    return (
         <>
          <section className='gray-banner d-flex align-items-center justify-content-center'>
				<div className="card col-6 m-auto border-0 shadow-sm">
					<div className='card-body'>
						<div className="w-100 text-center border-bottom mb-3">
							<h1 className='fs-20 fw-700'>Terms and Conditions</h1>
						</div>
						<div className="col">
                            <ul className='list-group'>
                                <li>Dear user, these terms and conditions govern the use of the service/s provided on the Telangana State Medical Council website.</li>
                                <li>PLEASE READ THIS TERMS OF SERVICE AGREEMENT CAREFULLY. BY USING THIS WEBSITE OR AVAILING SERVICES FROM THIS WEBSITE YOU AGREE TO BE BOUND BY ALL OF THE TERMS AND CONDITIONS OF THIS AGREEMENT.</li>
                                <li>Terms: “Telangana State Medical Council” refers to the owner of the website. The terms “us” or “we” refer to Telangana State Medical Council. The terms “you” or “your” refer to viewer or user of the website.</li>
                                <li>This Terms of Service Agreement (the "Agreement") governs your use of this website. This Agreement includes, and incorporates by this reference, the policies and guidelines referenced below. Telangana State Medical Council reserves the right to change or revise the terms and conditions of this Agreement at any time by posting any changes or a revised Agreement on this Website. The changed or revised Agreement will be effective immediately after it is posted on this Website. Your use of the Website following the posting any such changes or of a revised Agreement will constitute your acceptance of any such changes or revisions. Telangana State Medical Council encourages you to review this Agreement whenever you visit the Website to make sure that you understand the terms and conditions governing use of the Website. If you do not agree to this Agreement (including any referenced policies or guidelines), please immediately terminate your use of the Website.</li>
                                <li>Telangana State Medical Council creates the content on this Website, such content is protected by intellectual property laws of the India. Unauthorized use of the material may violate copyright, trademark, and/or other laws. You acknowledge that your use of the content on this Website is for personal, non- commercial use. Any links to third-party websites are provided solely as a convenience to you. We do not endorse the contents on any such third-party websites. We are not responsible for the content of or any damage that may result from your access to or reliance on these third-party websites. If you link to third- party websites, you do so at your own risk.</li>
                                <li>We are not responsible for any damages resulting from use of this website by anyone. You will not use the Website for illegal purposes. You will 1. abide by all applicable local, state, national, and international laws and regulations in your use of the Website (including laws regarding intellectual property); 2. Not to interfere with or disrupt the use and enjoyment of the Website by other users; 3. Not to resell or reproduce material on the Website; 4. Not to engage, directly or indirectly, in transmission of "spam", chain letters, junk mail or any other type of unsolicited communication; and 5. Not to defame, harass, abuse, or disrupt other users of the Website.</li>
                                <li>You may not copy, reproduce, transmit, distribute, or create derivative works of such content or information without express written authorization from us or the applicable third party (if third party content is at issue).</li>
                                <li>Keep your account secured: You are responsible for anything that happens through your account. 1. Try to choose a strong and secured password (Use combination of words, numbers and special characters). 2. Keep your password confidential and secured. 3. Do not share your password under any circumstances. 4. If you feel your password is compromised change it immediately.</li>
                                <li>We will not be deemed in default hereunder or held responsible for any cessation, interruption or delay in the performance of its obligations hereunder due to earthquake, flood, fire, storm, natural disaster, act of God, war, terrorism, armed conflict, labour strike, lockout, or boycott.</li>
                                <li>Telangana State Medical Council may at any time, in its sole discretion and without advance notice to you, cease operation of the Website.</li>
                                <li>This Agreement comprises the entire agreement between you and Telangana State Medical Council and supersedes any prior agreements pertaining to the subject matter contained herein.</li>
                                <li>The failure of Telangana State Medical Council to exercise or enforce any right or provision of this Agreement will not constitute a waiver of such right or provision. If any provision of this Agreement is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavour to give effect to the parties' intentions as reflected in the provision, and the other provisions of this Agreement remain in full force and effect.</li>
                                <li>This Website originates from Hyderabad, Telangana State. This Agreement will be governed by the laws of the State of Telangana without regard to its conflict of law principles to the contrary. Neither you nor we will commence or prosecute any suit, proceeding or claim to enforce the provisions of this Agreement, to recover damages for breach of or default of this Agreement, or otherwise arising under or by reason of this Agreement, other than in courts located in Hyderabad. By using this Website or availing services, you consent to the jurisdiction and venue of such courts in connection with any action, suit, proceeding or claim arising under or by reason of this Agreement. You hereby waive any right to trial by jury arising out of this Agreement and any related documents.</li>
                                <li>Telangana State Medical Council reserves the right to terminate your access to the Website if it reasonably believes, in its sole discretion, that you have breached any of the terms and conditions of this Agreement. If your access to the Website is terminated, we reserve the right to exercise whatever means it deems necessary to prevent unauthorized access of the Website. This Agreement will survive indefinitely unless and until Telangana State Medical Council chooses, in its sole discretion and without advance to you, to terminate it.</li>
                                <li>We make no representation that the website or services are appropriate or available for use in locations outside India. Users who access the website from outside India do so at their own risk and initiative and must bear all responsibility for compliance with any applicable local laws.</li>
                                <li>You may not assign your rights and obligations under this Agreement to anyone. We may assign its rights and obligations under this Agreement in its sole discretion and without advance notice to you.</li>
                                <li>Without limiting the generality of the foregoing, Telangana State Medical Council makes no warranty: 1. That the information provided on this website is accurate, reliable, complete, or timely; 2. That the links to third-party websites are to information that is accurate, reliable, complete, or timely; 3. No advice or information, whether oral or written, obtained by you from this website will create any warranty not expressly stated herein; 4. As to the results that may be obtained from the use of the services.</li>
                                <li>Telangana State Medical Council will not be liable for any direct, indirect, incidental, special or consequential damages in connection with this agreement or the services in any manner, including liabilities resulting from 1. the use or the inability to use the website content or services; 2. any transactions entered into through the website; or 3. any monetary loss you allege.</li>
                                <li>You will release, indemnify, defend and hold harmless Telangana State Medical Council from all liabilities, claims, damages, costs and expenses, including reasonable attorneys' fees and expenses, of third parties relating to or arising out of 1. this Agreement or the breach of your warranties, representations and obligations under this Agreement; 2. the website content or your use of the website content; 3. any intellectual property or other proprietary right of any person or entity; 4. your violation of any provision of this Agreement; or 5. any information or data you supplied to us. When Telangana State Medical Council is threatened with suit or sued by a third party, we may seek written assurances from you concerning your promise to indemnify us; your failure to provide such assurances may be considered by us to be a material breach of this Agreement. We will have the right to participate in any defense by you of a third-party claim related to your use of any of the Website content or services, with counsel of Telangana State Medical Council choice at its expense. We will reasonably cooperate in any defense by you of a third-party claim at your request and expense. You will have sole responsibility to defend us against any claim, but you must receive Telangana State Medical Council's prior written consent regarding any related settlement. The terms of this provision will survive any termination or cancellation of this Agreement or your use of the website or services.</li>
                                <li>BY USING THIS WEBSITE OR AVAILING THE SERVICES, YOU ACKNOWLEDGE THAT YOU HAVE READ AND AGREE TO BE BOUND BY THIS AGREEMENT AND ALL TERMS AND CONDITIONS ON THIS WEBSITE.</li>
                            </ul>
                        </div>
					</div>
				</div>
			</section>
         </>
    )
}

export default TermsConditions