export const urlPrefix = '/';

export const routes = {
    main: `${urlPrefix}`,
    home: `${urlPrefix}`,
    logout: `${urlPrefix}logout`,
    contact_us: `${urlPrefix}contact-us`,
    privacy_policy: `${urlPrefix}privacy-policy`,
    terms_and_conditions: `${urlPrefix}terms-and-conditions`,
    refund: `${urlPrefix}refund`,

    userpanal: `${urlPrefix}my-panal`,
    usereditprofile: `${urlPrefix}my-panal${urlPrefix}edit-profile`,
    user_data_edit:`${urlPrefix}my-panal${urlPrefix}edit-data`,
    provisional_registration: `${urlPrefix}my-panal${urlPrefix}provisional-registration`,
    provisional_edit: `${urlPrefix}my-panal${urlPrefix}edit-provisional`,
    provisional_duplicate: `${urlPrefix}my-panal${urlPrefix}provisional-duplicate`,
    final_registration: `${urlPrefix}my-panal${urlPrefix}final-registration`,
    final_edit: `${urlPrefix}my-panal${urlPrefix}edit-final`,
    final_duplicate: `${urlPrefix}my-panal${urlPrefix}final-duplicate`,
    additional_qualification_registration: `${urlPrefix}my-panal${urlPrefix}additional-qualification-registration`,
    edit_additional_qualification_registration: `${urlPrefix}my-panal${urlPrefix}edit_additional-qualification-registration`,
    additional_duplicate: `${urlPrefix}my-panal${urlPrefix}additional-duplicate`,
    good_standing_registration: `${urlPrefix}my-panal${urlPrefix}good-standing-registration`,
    good_standing_edit:`${urlPrefix}my-panal${urlPrefix}good-standing-edit`,
    good_standing_mci_registration: `${urlPrefix}my-panal${urlPrefix}good-standing-mci-registration`,
    noc_registration: `${urlPrefix}my-panal${urlPrefix}noc-registration`,
    noc_registration_edit:`${urlPrefix}my-panal${urlPrefix}edit-noc-registration`,
    temporary_registration: `${urlPrefix}my-panal${urlPrefix}temporary-registration`,
    final_renewal: `${urlPrefix}my-panal${urlPrefix}final-renewal`,
    edit_final_renewal: `${urlPrefix}my-panal${urlPrefix}edit-final-renewal`,
    change_of_name: `${urlPrefix}my-panal${urlPrefix}chnage-of-name`,
    prov_revalidation: `${urlPrefix}my-panal${urlPrefix}revalidation`,
    newregistration: `${urlPrefix}new-registration`,
    payment: `${urlPrefix}payment`,
    paymentsuccess: `${urlPrefix}paymentsuccess`,
    payment_failure: `${urlPrefix}payment_failure`,
    paymenterror: `${urlPrefix}paymentsuccess`,

    admin_dashboard: `${urlPrefix}admin`,
    admin_enable_edit: `${urlPrefix}admin${urlPrefix}enableEdit`,
    admin_my_work_items: `${urlPrefix}admin${urlPrefix}my-work-items`,
    provisional_registrations: `${urlPrefix}admin${urlPrefix}provisional_registrations`,
    admin_final_registrations: `${urlPrefix}admin${urlPrefix}final_registrations`,
    admin_provisional_view: `${urlPrefix}admin${urlPrefix}provisional_view`,
    admin_additional: `${urlPrefix}admin${urlPrefix}admin_additional`,
    admin_renewals: `${urlPrefix}admin${urlPrefix}admin_renewals`,
    admin_goodstanding: `${urlPrefix}admin${urlPrefix}admin_goodstanding`,
    admin_goodstanding_view: `${urlPrefix}admin${urlPrefix}admin_goodstanding_view`,
    admin_goodstanding_mci: `${urlPrefix}admin${urlPrefix}admin_goodstanding_mci`,
    admin_noc: `${urlPrefix}admin${urlPrefix}noc`,
    admin_final_reg_view: `${urlPrefix}admin${urlPrefix}final_reg_view`,
    admin_noc_reg_view:`${urlPrefix}admin${urlPrefix}noc_reg_view`,
    admin_additional_reg_view:`${urlPrefix}admin${urlPrefix}additional_reg_view`,
    admin_renewals_reg_view:`${urlPrefix}admin${urlPrefix}renewals_reg_view`,
    admin_changeofname_view:`${urlPrefix}admin${urlPrefix}changeofname_reg_view`,
    admin_revalidation_view:`${urlPrefix}admin${urlPrefix}revalidation_reg_view`,
    admin_employes_works: `${urlPrefix}admin/${urlPrefix}employees-works`,
    admin_notifications: `${urlPrefix}admin/${urlPrefix}notifications`,
    admin_settings: `${urlPrefix}admin/${urlPrefix}settings`,
    admin_logout: `${urlPrefix}admin/${urlPrefix}logout`,
    admin_login: `${urlPrefix}login`,
};